development:
    adapter: postgresql
    encoding: unicode
    database: basketball_quiz_dev
    pool: 5
    username: basketball
    password: 

test:
    adapter: postgresql
    encoding: unicode
    database: basketball_quiz_test
    pool: 5
    username: basketball
    password: 

production:
    adapter: postgresql
    encoding: unicode
    database: basketball_quiz_production
    pool: 5
    username: deploy
    password:
